install:
	# Link the python script so edits are reflected in realtime
	make uninstall
	chmod +x run_multiyear.py
	ln run_multiyear.py /usr/local/bin/run_multiyear


uninstall:
	# Remove the python script from the bin
	rm -f /usr/local/bin/run_multiyear
